# Generated by Django 6.0.3 on 2026-05-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField()),
                ('username', models.CharField(max_length=30)),
                ('phonenumber', models.TextField()),
                ('adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Log_in',
            fields=[
                ('userii_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Auth.userii')),
            ],
            bases=('Auth.userii',),
        ),
    ]
