# Generated by Django 4.2.29 on 2026-05-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log_in',
        ),
        migrations.DeleteModel(
            name='UserII',
        ),
    ]
