# Generated by Django 4.2.29 on 2026-05-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cb',
        ),
    ]
