# Generated by Django 4.2.29 on 2026-05-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_remove_order_cb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='orderis',
            field=models.BooleanField(default=True),
        ),
    ]
