# Generated by Django 6.0.3 on 2026-05-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_remove_order_items_order_orderis'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.ingredient')),
            ],
        ),
        migrations.DeleteModel(
            name='ImproveappendedDish',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderis',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='extra_ingredients',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='removed_ingredients',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('done', 'Done')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitemingredient',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_adjustments', to='Menu.orderitem'),
        ),
    ]
